### ISSUE TITLE
User Validator 적용

### ISSUE THREAD

**Issue by hyukjin-lee** [unnies/baeminchan#25]

**Comment by minsungryu** [comment]
비밀번호 Validator 추가
`^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{8,16}$`
참고 http://enzycut.tistory.com/entry/JAVA-%ED%8C%A8%EC%8A%A4%EC%9B%8C%EB%93%9C-%EC%A0%95%EA%B7%9C%EC%8B%9D-Regex

**Comment by minsungryu** [comment]
휴대폰 번호 Validator 추가
`(01[016789])-(\\d{3,4})-(\\d{4})`

단, 010일 때 가운데 번호가 3자리인 경우는 파악하지 않는다.

**Comment by minsungryu** [comment]
사용자의 이름은 `[가-힣]{2,16}`을 통해 한글만 입력받는다.(우선은)

**Comment by minsungryu** [comment]
이메일은 출처가 어디죠?
`^[_a-z0-9-]+(.[_a-z0-9-]+)*@(?:\w+\.)+\w+$`

**Comment by minsungryu** [comment]
Validator 적용은 좋으나 과한 구현이지 않을까 하는 피드백이 있었음.
